version: 0.1
phases:
  install:
    commands:
      - echo Installing source NPM dependencies
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started
      - ng build --prod --configuration=${BUILD_ENV}
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes