version: 0.1
phases:
  install:
    commands:
      - echo Installing source NPM dependencies
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started ${BUILD_ENV}
      - npm install
      - ng build --prod --configuration=production
  post_build:
    commands:
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - aws configure set preview.cloudfront true
      - echo Build completed ${S3_BUCKET}
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes